version: '3'

services:
  it-hub:
    build: .
    image: it-hub-back
    container_name: it-hub-back-container
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: student_hub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  pgdata: